type TemplateFile = {
  path: string;
  language: string;
  purpose: string;
  content: string;
};

type TemplateInput = {
  prompt: string;
};

function getAppName(prompt: string) {
  const lower = prompt.toLowerCase();

  if (lower.includes("freelancer")) return "Freelancer Invoice Tracker";
  if (lower.includes("invoice")) return "Invoice Tracker";

  return "Billing Dashboard";
}

function getSlug(name: string) {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "invoice-tracker"
  );
}

export function createInvoiceTrackerTemplate({ prompt }: TemplateInput) {
  const appName = getAppName(prompt);
  const slug = getSlug(appName);

  const packageJson = `{
  "name": "${slug}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.35",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  }
}
`;

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`;

  const nextEnv = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file was generated by Ember.
`;

  const tsconfigJson = `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

  const layoutTsx = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${appName}",
  description: "Generated by Ember.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

  const pageTsx = `"use client";

import { type ChangeEvent, type FormEvent, useMemo, useState } from "react";

type InvoiceStatus = "Draft" | "Sent" | "Paid" | "Overdue";

type Client = {
  id: string;
  name: string;
  contact: string;
  email: string;
  phone: string;
};

type Invoice = {
  id: string;
  clientId: string;
  title: string;
  amount: number;
  status: InvoiceStatus;
  dueDate: string;
  notes: string;
};

const currencyFormatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  maximumFractionDigits: 0,
});

const initialClients: Client[] = [
  {
    id: "client-1",
    name: "Brightline Studio",
    contact: "Dana Lewis",
    email: "dana@brightline.example",
    phone: "(555) 014-8001",
  },
  {
    id: "client-2",
    name: "North Harbor Realty",
    contact: "Marcus Reed",
    email: "marcus@northharbor.example",
    phone: "(555) 014-8002",
  },
  {
    id: "client-3",
    name: "Stonebridge Consulting",
    contact: "Priya Shah",
    email: "priya@stonebridge.example",
    phone: "(555) 014-8003",
  },
];

const initialInvoices: Invoice[] = [
  {
    id: "inv-1001",
    clientId: "client-1",
    title: "Website refresh deposit",
    amount: 2400,
    status: "Sent",
    dueDate: "May 3",
    notes: "Initial deposit for homepage redesign and brand cleanup.",
  },
  {
    id: "inv-1002",
    clientId: "client-2",
    title: "Lead dashboard MVP",
    amount: 5200,
    status: "Draft",
    dueDate: "May 10",
    notes: "Draft invoice waiting on final project scope approval.",
  },
  {
    id: "inv-1003",
    clientId: "client-3",
    title: "Monthly support retainer",
    amount: 1800,
    status: "Paid",
    dueDate: "Paid Apr 21",
    notes: "April support and maintenance retainer.",
  },
  {
    id: "inv-1004",
    clientId: "client-2",
    title: "CRM cleanup balance",
    amount: 950,
    status: "Overdue",
    dueDate: "Apr 18",
    notes: "Follow up this week before sending a reminder.",
  },
];

function getStatusClass(status: InvoiceStatus) {
  return "status-badge " + status.toLowerCase();
}

export default function Page() {
  const [clients, setClients] = useState<Client[]>(initialClients);
  const [invoices, setInvoices] = useState<Invoice[]>(initialInvoices);
  const [search, setSearch] = useState("");

  const [clientForm, setClientForm] = useState({
    name: "",
    contact: "",
    email: "",
    phone: "",
  });

  const [invoiceForm, setInvoiceForm] = useState({
    clientId: initialClients[0]?.id ?? "",
    title: "",
    amount: "",
    dueDate: "",
    notes: "",
  });

  const stats = useMemo(() => {
    const unpaid = invoices.filter((invoice) => invoice.status !== "Paid");
    const paid = invoices.filter((invoice) => invoice.status === "Paid");
    const overdue = invoices.filter((invoice) => invoice.status === "Overdue");

    return [
      {
        label: "Outstanding",
        value: currencyFormatter.format(
          unpaid.reduce((total, invoice) => total + invoice.amount, 0),
        ),
        helper: "Open invoice balance",
      },
      {
        label: "Paid",
        value: currencyFormatter.format(
          paid.reduce((total, invoice) => total + invoice.amount, 0),
        ),
        helper: "Collected revenue",
      },
      {
        label: "Clients",
        value: clients.length,
        helper: "Billing relationships",
      },
      {
        label: "Overdue",
        value: overdue.length,
        helper: "Needs follow-up",
      },
    ];
  }, [clients.length, invoices]);

  const filteredInvoices = useMemo(() => {
    const query = search.trim().toLowerCase();

    if (!query) return invoices;

    return invoices.filter((invoice) => {
      const client = clients.find((item) => item.id === invoice.clientId);

      return [
        invoice.title,
        invoice.status,
        invoice.notes,
        invoice.dueDate,
        client?.name,
        client?.contact,
        client?.email,
        client?.phone,
      ]
        .join(" ")
        .toLowerCase()
        .includes(query);
    });
  }, [clients, invoices, search]);

  function getClient(clientId: string) {
    return clients.find((client) => client.id === clientId);
  }

  function handleClientChange(event: ChangeEvent<HTMLInputElement>) {
    const { name, value } = event.target;

    setClientForm((current) => ({
      ...current,
      [name]: value,
    }));
  }

  function handleInvoiceChange(
    event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>,
  ) {
    const { name, value } = event.target;

    setInvoiceForm((current) => ({
      ...current,
      [name]: value,
    }));
  }

  function handleClientSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!clientForm.name.trim()) return;

    const newClient: Client = {
      id: "client-" + Date.now(),
      name: clientForm.name.trim(),
      contact: clientForm.contact.trim() || "Primary contact",
      email: clientForm.email.trim() || "No email provided",
      phone: clientForm.phone.trim() || "No phone provided",
    };

    setClients((current) => [newClient, ...current]);
    setInvoiceForm((current) => ({
      ...current,
      clientId: newClient.id,
    }));

    setClientForm({
      name: "",
      contact: "",
      email: "",
      phone: "",
    });
  }

  function handleInvoiceSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!invoiceForm.title.trim()) return;

    const newInvoice: Invoice = {
      id: "inv-" + Date.now(),
      clientId: invoiceForm.clientId,
      title: invoiceForm.title.trim(),
      amount: Number(invoiceForm.amount) || 0,
      status: "Draft",
      dueDate: invoiceForm.dueDate.trim() || "Not set",
      notes: invoiceForm.notes.trim() || "No notes yet.",
    };

    setInvoices((current) => [newInvoice, ...current]);

    setInvoiceForm((current) => ({
      ...current,
      title: "",
      amount: "",
      dueDate: "",
      notes: "",
    }));
  }

  function moveInvoiceStatus(id: string) {
    setInvoices((current) =>
      current.map((invoice) => {
        if (invoice.id !== id) return invoice;

        const nextStatus =
          invoice.status === "Draft"
            ? "Sent"
            : invoice.status === "Sent"
              ? "Paid"
              : invoice.status === "Overdue"
                ? "Sent"
                : "Draft";

        return {
          ...invoice,
          status: nextStatus,
        };
      }),
    );
  }

  return (
    <main className="page-shell">
      <section className="hero-card">
        <div>
          <p className="eyebrow">Invoice Tracker</p>
          <h1>Professional billing dashboard</h1>
          <p className="hero-copy">
            Track clients, invoices, payment status, overdue balances, and
            follow-up work from one clean workspace.
          </p>
        </div>
</section>

      <section className="stat-grid" aria-label="Invoice overview">
        {stats.map((stat) => (
          <article className="stat-card" key={stat.label}>
            <span>{stat.label}</span>
            <strong>{stat.value}</strong>
            <p>{stat.helper}</p>
          </article>
        ))}
      </section>

      <section className="dashboard-grid">
        <article className="panel" id="new-client">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Client records</p>
              <h2>Add a client</h2>
            </div>
          </div>

          <form className="stacked-form" onSubmit={handleClientSubmit}>
            <div className="form-row">
              <label htmlFor="client-name">Client / company</label>
              <input
                id="client-name"
                name="name"
                type="text"
                value={clientForm.name}
                onChange={handleClientChange}
                placeholder="Client or company name"
                required
              />
            </div>

            <div className="form-row">
              <label htmlFor="client-contact">Contact person</label>
              <input
                id="client-contact"
                name="contact"
                type="text"
                value={clientForm.contact}
                onChange={handleClientChange}
                placeholder="Primary contact"
              />
            </div>

            <div className="form-two-column">
              <div className="form-row">
                <label htmlFor="client-email">Email</label>
                <input
                  id="client-email"
                  name="email"
                  type="email"
                  value={clientForm.email}
                  onChange={handleClientChange}
                  placeholder="billing@example.com"
                />
              </div>

              <div className="form-row">
                <label htmlFor="client-phone">Phone</label>
                <input
                  id="client-phone"
                  name="phone"
                  type="tel"
                  value={clientForm.phone}
                  onChange={handleClientChange}
                  placeholder="(555) 000-0000"
                />
              </div>
            </div>

            <button className="button primary full-width" type="submit">
              Save client
            </button>
          </form>
        </article>

        <article className="panel" id="new-invoice">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">New invoice</p>
              <h2>Create billing record</h2>
            </div>
          </div>

          <form className="stacked-form" onSubmit={handleInvoiceSubmit}>
            <div className="form-row">
              <label htmlFor="clientId">Client</label>
              <select
                id="clientId"
                name="clientId"
                value={invoiceForm.clientId}
                onChange={handleInvoiceChange}
              >
                {clients.map((client) => (
                  <option key={client.id} value={client.id}>
                    {client.name}
                  </option>
                ))}
              </select>
            </div>

            <div className="form-row">
              <label htmlFor="title">Invoice title</label>
              <input
                id="title"
                name="title"
                type="text"
                value={invoiceForm.title}
                onChange={handleInvoiceChange}
                placeholder="Project milestone, retainer, or service"
                required
              />
            </div>

            <div className="form-two-column">
              <div className="form-row">
                <label htmlFor="amount">Amount</label>
                <input
                  id="amount"
                  name="amount"
                  type="number"
                  min="0"
                  value={invoiceForm.amount}
                  onChange={handleInvoiceChange}
                  placeholder="1500"
                />
              </div>

              <div className="form-row">
                <label htmlFor="dueDate">Due date</label>
                <input
                  id="dueDate"
                  name="dueDate"
                  type="text"
                  value={invoiceForm.dueDate}
                  onChange={handleInvoiceChange}
                  placeholder="May 15"
                />
              </div>
            </div>

            <div className="form-row">
              <label htmlFor="notes">Notes</label>
              <textarea
                id="notes"
                name="notes"
                value={invoiceForm.notes}
                onChange={handleInvoiceChange}
                placeholder="Scope, payment terms, reminder details, or next action"
                rows={4}
              />
            </div>

            <button className="button primary full-width" type="submit">
              Save invoice
            </button>
          </form>
        </article>
      </section>

      <section className="dashboard-grid">
        <article className="panel">
          <div className="panel-heading">
            <div>
              <p className="eyebrow">Client accounts</p>
              <h2>Clients</h2>
            </div>
          </div>

          <div className="record-list">
            {clients.map((client) => (
              <div className="record-card" key={client.id}>
                <div className="record-topline">
                  <div>
                    <h3>{client.name}</h3>
                    <p>{client.contact}</p>
                  </div>
                </div>

                <div className="record-meta">
                  <span>{client.email}</span>
                  <span>{client.phone}</span>
                </div>
              </div>
            ))}
          </div>
        </article>

        <article className="panel">
          <div className="panel-heading split">
            <div>
              <p className="eyebrow">Invoice list</p>
              <h2>Billing records</h2>
            </div>

            <label className="search-label" htmlFor="invoice-search">
              <span className="sr-only">Search invoices</span>
              <input
                id="invoice-search"
                type="search"
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder="Search invoices or clients"
              />
            </label>
          </div>

          <div className="record-list">
            {filteredInvoices.map((invoice) => {
              const client = getClient(invoice.clientId);

              return (
                <div className="record-card" key={invoice.id}>
                  <div className="record-topline">
                    <div>
                      <h3>{invoice.title}</h3>
                      <p>
                        {client?.name || "Unknown client"} · {invoice.dueDate} ·{" "}
                        {currencyFormatter.format(invoice.amount)}
                      </p>
                    </div>

                    <span className={getStatusClass(invoice.status)}>
                      {invoice.status}
                    </span>
                  </div>

                  <p className="record-note">{invoice.notes}</p>

                  <div className="record-meta">
                    <span>{client?.email || "No email"}</span>
                    <button
                      className="table-action"
                      type="button"
                      onClick={() => moveInvoiceStatus(invoice.id)}
                    >
                      Move status
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </article>
      </section>
    </main>
  );
}
`;

  const globalsCss = `:root {
  --background: #f4f6f8;
  --surface: #ffffff;
  --surface-soft: #f8fafc;
  --text: #142033;
  --muted: #64748b;
  --border: #d8dee8;
  --primary: #1f3a5f;
  --primary-dark: #152a43;
  --success: #166534;
  --warning: #92400e;
  --danger: #991b1b;
  --shadow: 0 10px 24px rgba(15, 23, 42, 0.07);
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background: var(--background);
  color: var(--text);
  font-family:
    Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
    sans-serif;
}

button,
input,
select,
textarea {
  font: inherit;
}

.page-shell {
  width: min(1280px, calc(100% - 32px));
  margin: 0 auto;
  padding: 24px 0 40px;
}

.hero-card,
.panel,
.stat-card {
  background: var(--surface);
  border: 1px solid var(--border);
  box-shadow: var(--shadow);
}

.hero-card {
  display: flex;
  justify-content: space-between;
  gap: 20px;
  align-items: flex-start;
  border-radius: 14px;
  padding: 24px;
  margin-bottom: 18px;
  overflow: hidden;
}

.hero-card > div:first-child {
  min-width: 0;
  flex: 1;
}

.eyebrow {
  margin: 0 0 8px;
  color: var(--primary);
  font-size: 0.78rem;
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-weight: 800;
}

h1,
h2,
h3,
p {
  margin-top: 0;
}

h1 {
  margin-bottom: 8px;
  font-size: clamp(2rem, 3vw, 2.8rem);
  line-height: 1.05;
  overflow-wrap: anywhere;
}

h2 {
  margin-bottom: 0;
  font-size: 1.35rem;
}

h3 {
  margin-bottom: 4px;
  font-size: 1rem;
}

.hero-copy {
  max-width: 820px;
  color: var(--muted);
  font-size: 0.98rem;
  line-height: 1.55;
  margin-bottom: 0;
  overflow-wrap: anywhere;
}


.button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: 0;
  border-radius: 999px;
  padding: 12px 18px;
  font-weight: 800;
  text-decoration: none;
  cursor: pointer;
}

.button.primary {
  background: var(--primary);
  color: white;
}

.button.primary:hover {
  background: var(--primary-dark);
}

.button.secondary {
  background: var(--surface-soft);
  color: var(--text);
  border: 1px solid var(--border);
}

.full-width {
  width: 100%;
}

.stat-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(150px, 1fr));
  gap: 12px;
  margin-bottom: 18px;
}

.stat-card {
  border-radius: 12px;
  padding: 16px;
  min-height: 112px;
}

.stat-card span {
  color: var(--muted);
  font-size: 0.9rem;
  font-weight: 700;
}

.stat-card strong {
  display: block;
  margin: 6px 0;
  font-size: 1.75rem;
}

.stat-card p {
  margin: 0;
  color: var(--muted);
  line-height: 1.5;
}

.dashboard-grid {
  display: grid;
  grid-template-columns: minmax(0, 0.95fr) minmax(0, 1.05fr);
  gap: 16px;
  margin-bottom: 16px;
}

.panel {
  border-radius: 12px;
  padding: 18px;
}

.wide-panel {
  margin-bottom: 20px;
}

.panel-heading {
  margin-bottom: 18px;
}

.panel-heading.split {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  align-items: center;
}

.stacked-form {
  display: grid;
  gap: 12px;
}

.form-two-column {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14px;
}

.form-row {
  display: grid;
  gap: 7px;
}

label {
  color: var(--muted);
  font-size: 0.86rem;
  font-weight: 800;
}

input,
select,
textarea {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 10px 12px;
  background: white;
  color: var(--text);
  outline: none;
}

input:focus,
select:focus,
textarea:focus {
  border-color: var(--primary);
  box-shadow: 0 0 0 4px rgba(31, 58, 95, 0.12);
}

.record-list {
  display: grid;
  gap: 14px;
}

.record-card {
  border: 1px solid var(--border);
  background: var(--surface-soft);
  border-radius: 12px;
  padding: 16px;
}

.record-topline,
.record-meta {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  align-items: flex-start;
}

.record-topline p {
  color: var(--muted);
  margin-bottom: 0;
}

.record-meta {
  color: var(--muted);
  font-size: 0.83rem;
  flex-wrap: wrap;
}

.status-badge {
  display: inline-flex;
  align-items: center;
  white-space: nowrap;
  border-radius: 999px;
  padding: 6px 10px;
  font-size: 0.75rem;
  font-weight: 900;
  background: #e2e8f0;
  color: #334155;
}

.status-badge.draft {
  background: #e2e8f0;
  color: #334155;
}

.status-badge.sent {
  background: #dbeafe;
  color: #1d4ed8;
}

.status-badge.paid {
  background: #dcfce7;
  color: #166534;
}

.status-badge.overdue {
  background: #fee2e2;
  color: #991b1b;
}

.search-label {
  min-width: 280px;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
}

.table-wrap {
  overflow-x: auto;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  padding: 14px;
  border-bottom: 1px solid var(--border);
  text-align: left;
  vertical-align: top;
}

th {
  color: var(--muted);
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

td span {
  display: block;
  color: var(--muted);
  margin-top: 4px;
  font-size: 0.86rem;
}

.table-action {
  border: 1px solid var(--border);
  background: white;
  border-radius: 999px;
  padding: 8px 12px;
  cursor: pointer;
  font-weight: 800;
}

.table-action:hover {
  background: var(--surface-soft);
}

@media (max-width: 1100px) {
  .hero-card {
    flex-direction: column;
    align-items: flex-start;
  }
}

@media (max-width: 900px) {
  .panel-heading.split,
  .record-topline {
    flex-direction: column;
    align-items: flex-start;
  }

  .stat-grid,
  .dashboard-grid,
  .form-two-column {
    grid-template-columns: 1fr;
  }

  .search-label {
    width: 100%;
    min-width: 0;
  }
}
`;

  const readme = `# ${appName}

${prompt}

## Run locally

npm install

npm run dev

Open the local URL printed in the terminal.

## Generated by Ember

This starter is intentionally local-first and uses sample data. The next step is usually adding persistence, auth, deployment, payment records, PDF invoice export, or client-specific workflow logic.
`;

  const previewHtml = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${appName} Preview</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {
      margin: 0;
      font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f4f6f8;
      color: #142033;
    }
    .shell {
      max-width: 430px;
      margin: 0 auto;
      min-height: 100vh;
      background: white;
      box-shadow: 0 10px 24px rgba(15, 23, 42, 0.12);
    }
    .hero {
      background: linear-gradient(135deg, #1f3a5f, #2f4f6f);
      color: white;
      padding: 28px;
      border-radius: 0 0 20px 20px;
    }
    .badge {
      display: inline-flex;
      background: rgba(255,255,255,0.18);
      border-radius: 999px;
      padding: 7px 10px;
      font-size: 12px;
      font-weight: 800;
      margin-bottom: 14px;
    }
    h1 {
      margin: 0 0 10px;
      font-size: 30px;
      line-height: 1;
    }
    p {
      margin: 0;
      line-height: 1.5;
    }
    .content {
      padding: 22px;
      display: grid;
      gap: 14px;
    }
    .stats {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 12px;
    }
    .card {
      border: 1px solid #d8dee8;
      border-radius: 14px;
      padding: 16px;
      background: #f8fafc;
    }
    .label {
      color: #64748b;
      font-size: 12px;
      font-weight: 800;
    }
    .value {
      display: block;
      margin-top: 6px;
      font-size: 24px;
      font-weight: 900;
    }
  </style>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <div class="badge">Invoice Tracker</div>
      <h1>${appName}</h1>
      <p>Track invoices, clients, payment status, and follow-up work.</p>
    </section>

    <section class="content">
      <div class="stats">
        <div class="card">
          <div class="label">Outstanding</div>
          <strong class="value">$8.6k</strong>
        </div>
        <div class="card">
          <div class="label">Paid</div>
          <strong class="value">$1.8k</strong>
        </div>
        <div class="card">
          <div class="label">Sent</div>
          <strong class="value">1</strong>
        </div>
        <div class="card">
          <div class="label">Overdue</div>
          <strong class="value">1</strong>
        </div>
      </div>

      <div class="card">
        <strong>Brightline Studio</strong>
        <p>Website refresh deposit · Sent · $2,400</p>
      </div>
      <div class="card">
        <strong>North Harbor Realty</strong>
        <p>Lead dashboard MVP · Draft · $5,200</p>
      </div>
      <div class="card">
        <strong>Stonebridge Consulting</strong>
        <p>Monthly support retainer · Paid · $1,800</p>
      </div>
    </section>
  </main>
</body>
</html>
`;

  const files: TemplateFile[] = [
    {
      path: "package.json",
      language: "json",
      purpose: "Project dependencies and scripts.",
      content: packageJson,
    },
    {
      path: "next.config.mjs",
      language: "javascript",
      purpose: "Next.js configuration.",
      content: nextConfig,
    },
    {
      path: "next-env.d.ts",
      language: "ts",
      purpose: "Next.js type declarations.",
      content: nextEnv,
    },
    {
      path: "tsconfig.json",
      language: "json",
      purpose: "TypeScript configuration.",
      content: tsconfigJson,
    },
    {
      path: "app/layout.tsx",
      language: "tsx",
      purpose: "Root app layout.",
      content: layoutTsx,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      purpose: "Invoice tracker dashboard and workflow.",
      content: pageTsx,
    },
    {
      path: "app/globals.css",
      language: "css",
      purpose: "Global styles and app classes.",
      content: globalsCss,
    },
    {
      path: "README.md",
      language: "markdown",
      purpose: "Setup and run instructions.",
      content: readme,
    },
  ];

  return {
    appName,
    slug,
    platform: "business_tool",
    framework: "Next.js",
    summary:
      "A professional local-first invoice tracker for freelancers and small businesses with client records, invoice status, payment tracking, and dashboard metrics.",
    previewHtml,
    previewType: "interactive_html",
    previewNotes:
      "This preview shows the generated invoice tracker layout. The exported project includes a runnable Next.js app.",
    files,
    nextSteps: [
      "Export the ZIP.",
      "Run npm install.",
      "Run npm run dev.",
      "Ask Ember to add persistence, PDF invoice export, Stripe payments, or client authentication.",
    ],
  };
}
