type TemplateFile = {
  path: string;
  language: string;
  purpose: string;
  content: string;
};

type TemplateInput = {
  prompt: string;
};

function titleCase(value: string) {
  return value
    .replace(/[^a-zA-Z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 4)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(" ");
}

function getAppName(prompt: string) {
  const lower = prompt.toLowerCase();

  if (lower.includes("invoice")) return "Invoice Tracker";
  if (lower.includes("habit")) return "Habit Tracker";
  if (lower.includes("booking")) return "Booking Manager";
  if (lower.includes("fitness")) return "Fitness Tracker";
  if (lower.includes("todo") || lower.includes("to do")) return "Todo App";
  if (lower.includes("restaurant")) return "Restaurant Manager";
  if (lower.includes("lead")) return "Lead Tracker";
  if (lower.includes("crm")) return "CRM Starter";

  return titleCase(prompt) || "Generated App";
}

function slugify(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "generated-app"
  );
}

function getDomainLabel(prompt: string) {
  const lower = prompt.toLowerCase();

  if (lower.includes("invoice")) return "Invoices";
  if (lower.includes("habit")) return "Habits";
  if (lower.includes("booking")) return "Bookings";
  if (lower.includes("fitness")) return "Workouts";
  if (lower.includes("restaurant")) return "Orders";
  if (lower.includes("lead")) return "Leads";
  if (lower.includes("crm")) return "Customers";
  if (lower.includes("budget")) return "Expenses";

  return "Records";
}

function getPrimaryAction(prompt: string) {
  const lower = prompt.toLowerCase();

  if (lower.includes("invoice")) return "Create invoice";
  if (lower.includes("habit")) return "Add habit";
  if (lower.includes("booking")) return "Add booking";
  if (lower.includes("fitness")) return "Log workout";
  if (lower.includes("restaurant")) return "Add order";
  if (lower.includes("lead")) return "Capture lead";
  if (lower.includes("crm")) return "Add customer";
  if (lower.includes("budget")) return "Add expense";

  return "Add record";
}

export function createUniversalNextTemplate({ prompt }: TemplateInput) {
  const appName = getAppName(prompt);
  const slug = slugify(appName);
  const domainLabel = getDomainLabel(prompt);
  const primaryAction = getPrimaryAction(prompt);

  const packageJson = `{
  "name": "${slug}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.35",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  }
}
`;

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`;

  const nextEnv = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file was generated by Ember.
`;

  const tsconfigJson = `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

  const layoutTsx = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(appName)},
  description: "Generated by Ember.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

  const pageTsx = `"use client";

import { type FormEvent, useMemo, useState } from "react";

type ItemStatus = "New" | "Active" | "Review" | "Done";

type Item = {
  id: string;
  title: string;
  detail: string;
  status: ItemStatus;
};

const appTitle = ${JSON.stringify(appName)};
const appPrompt = ${JSON.stringify(prompt)};
const domainLabel = ${JSON.stringify(domainLabel)};
const primaryAction = ${JSON.stringify(primaryAction)};

const starterItems: Item[] = [
  {
    id: "item-1",
    title: domainLabel + " Alpha",
    detail: "Primary starter record created by Ember.",
    status: "Active",
  },
  {
    id: "item-2",
    title: domainLabel + " Beta",
    detail: "Needs review, a decision, or a follow-up.",
    status: "Review",
  },
  {
    id: "item-3",
    title: domainLabel + " Gamma",
    detail: "Recently added starter record.",
    status: "New",
  },
];

function getStatusClass(status: ItemStatus) {
  return "status " + status.toLowerCase();
}

export default function Page() {
  const [items, setItems] = useState<Item[]>(starterItems);
  const [title, setTitle] = useState("");
  const [detail, setDetail] = useState("");

  const stats = useMemo(() => {
    return [
      {
        label: "Total " + domainLabel,
        value: items.length,
      },
      {
        label: "Active",
        value: items.filter((item) => item.status === "Active").length,
      },
      {
        label: "Review",
        value: items.filter((item) => item.status === "Review").length,
      },
      {
        label: "Done",
        value: items.filter((item) => item.status === "Done").length,
      },
    ];
  }, [items]);

  function addItem(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!title.trim()) return;

    const newItem: Item = {
      id: "item-" + Date.now(),
      title: title.trim(),
      detail: detail.trim() || "No details yet.",
      status: "New",
    };

    setItems((current) => [newItem, ...current]);
    setTitle("");
    setDetail("");
  }

  function advanceStatus(id: string) {
    setItems((current) =>
      current.map((item) => {
        if (item.id !== id) return item;

        const nextStatus =
          item.status === "New"
            ? "Active"
            : item.status === "Active"
              ? "Review"
              : item.status === "Review"
                ? "Done"
                : "New";

        return {
          ...item,
          status: nextStatus,
        };
      }),
    );
  }

  return (
    <main className="page-shell">
      <section className="hero">
        <p className="eyebrow">Generated by Ember</p>
        <h1>{appTitle}</h1>
        <p className="hero-copy">{appPrompt}</p>
      </section>

      <section className="stats-grid">
        {stats.map((stat) => (
          <article className="stat-card" key={stat.label}>
            <span>{stat.label}</span>
            <strong>{stat.value}</strong>
          </article>
        ))}
      </section>

      <section className="dashboard-grid">
        <article className="panel">
          <p className="eyebrow">Create</p>
          <h2>{primaryAction}</h2>

          <form className="form" onSubmit={addItem}>
            <label>
              Title
              <input
                value={title}
                onChange={(event) => setTitle(event.target.value)}
                placeholder="Record title"
              />
            </label>

            <label>
              Details
              <textarea
                value={detail}
                onChange={(event) => setDetail(event.target.value)}
                placeholder="Notes, description, or next action"
                rows={5}
              />
            </label>

            <button className="button" type="submit">
              Save record
            </button>
          </form>
        </article>

        <article className="panel">
          <p className="eyebrow">Workspace</p>
          <h2>{domainLabel}</h2>

          <div className="record-list">
            {items.map((item) => (
              <div className="record-card" key={item.id}>
                <div>
                  <h3>{item.title}</h3>
                  <p>{item.detail}</p>
                </div>

                <div className="record-actions">
                  <span className={getStatusClass(item.status)}>
                    {item.status}
                  </span>

                  <button type="button" onClick={() => advanceStatus(item.id)}>
                    Move status
                  </button>
                </div>
              </div>
            ))}
          </div>
        </article>
      </section>
    </main>
  );
}
`;

  const globalsCss = `:root {
  --background: #f4f6f8;
  --surface: #ffffff;
  --surface-soft: #f1f5f9;
  --text: #132033;
  --muted: #64748b;
  --border: #d9e2ec;
  --primary: #1f3a5f;
  --primary-dark: #152a43;
  --shadow: 0 10px 24px rgba(15, 23, 42, 0.07);
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background:
    var(--background);
  color: var(--text);
  font-family:
    Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
    sans-serif;
}

button,
input,
textarea {
  font: inherit;
}

.page-shell {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 36px 0 60px;
}

.hero,
.panel,
.stat-card {
  background: rgba(255, 255, 255, 0.94);
  border: 1px solid var(--border);
  box-shadow: var(--shadow);
}

.hero {
  border-radius: 16px;
  padding: 34px;
  margin-bottom: 20px;
}

.eyebrow {
  margin: 0 0 8px;
  color: var(--primary);
  font-size: 0.78rem;
  font-weight: 900;
  letter-spacing: 0.12em;
  text-transform: uppercase;
}

h1,
h2,
h3,
p {
  margin-top: 0;
}

h1 {
  margin-bottom: 12px;
  font-size: clamp(2rem, 4vw, 3.2rem);
  line-height: 1;
}

h2 {
  margin-bottom: 16px;
  font-size: 1.35rem;
}

h3 {
  margin-bottom: 6px;
}

.hero-copy {
  max-width: 720px;
  color: var(--muted);
  font-size: 1.08rem;
  line-height: 1.7;
  margin-bottom: 0;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 16px;
  margin-bottom: 20px;
}

.stat-card {
  border-radius: 14px;
  padding: 22px;
}

.stat-card span {
  color: var(--muted);
  font-weight: 800;
}

.stat-card strong {
  display: block;
  margin-top: 8px;
  font-size: 2rem;
}

.dashboard-grid {
  display: grid;
  grid-template-columns: 0.8fr 1.2fr;
  gap: 20px;
}

.panel {
  border-radius: 14px;
  padding: 24px;
}

.form {
  display: grid;
  gap: 16px;
}

label {
  display: grid;
  gap: 8px;
  color: var(--muted);
  font-size: 0.88rem;
  font-weight: 800;
}

input,
textarea {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 12px 14px;
  outline: none;
  color: var(--text);
  background: white;
}

input:focus,
textarea:focus {
  border-color: var(--primary);
  box-shadow: 0 0 0 4px rgba(37, 99, 235, 0.12);
}

.button,
.record-actions button {
  border: 0;
  border-radius: 999px;
  padding: 12px 16px;
  background: var(--primary);
  color: white;
  font-weight: 900;
  cursor: pointer;
}

.button:hover,
.record-actions button:hover {
  background: var(--primary-dark);
}

.record-list {
  display: grid;
  gap: 14px;
}

.record-card {
  display: grid;
  gap: 14px;
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 16px;
  background: var(--surface-soft);
}

.record-card p {
  color: var(--muted);
  line-height: 1.5;
  margin-bottom: 0;
}

.record-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
}

.status {
  display: inline-flex;
  border-radius: 999px;
  padding: 6px 10px;
  font-size: 0.75rem;
  font-weight: 900;
  background: #dbeafe;
  color: #1d4ed8;
}

.status.new {
  background: #e2e8f0;
  color: #334155;
}

.status.review {
  background: #fef3c7;
  color: #92400e;
}

.status.done {
  background: #dcfce7;
  color: #166534;
}

@media (max-width: 900px) {
  .stats-grid,
  .dashboard-grid {
    grid-template-columns: 1fr;
  }
}
`;

  const previewHtml = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${appName} Preview</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {
      margin: 0;
      font-family: Inter, system-ui, sans-serif;
      background: #f6f8fb;
      color: #132033;
    }
    .shell {
      max-width: 430px;
      margin: 0 auto;
      min-height: 100vh;
      background: white;
      box-shadow: 0 20px 50px rgba(15, 23, 42, 0.18);
    }
    .hero {
      background: linear-gradient(135deg, #1f3a5f, #2f4f6f);
      color: white;
      padding: 28px;
      border-radius: 0 0 28px 28px;
    }
    .badge {
      display: inline-flex;
      background: rgba(255,255,255,0.18);
      border-radius: 999px;
      padding: 7px 10px;
      font-size: 12px;
      font-weight: 800;
      margin-bottom: 14px;
    }
    h1 {
      margin: 0 0 10px;
      font-size: 32px;
      line-height: 1;
    }
    p {
      margin: 0;
      line-height: 1.5;
    }
    .content {
      padding: 22px;
      display: grid;
      gap: 14px;
    }
    .card {
      border: 1px solid #d9e2ec;
      border-radius: 12px;
      padding: 16px;
      background: #f8fafc;
    }
  </style>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <div class="badge">Generated App</div>
      <h1>${appName}</h1>
      <p>${prompt}</p>
    </section>
    <section class="content">
      <div class="card"><strong>Dashboard</strong><p>Starter workspace generated by Ember.</p></div>
      <div class="card"><strong>Create records</strong><p>Add and track items from one place.</p></div>
      <div class="card"><strong>Recent activity</strong><p>See the latest updates and next actions.</p></div>
    </section>
  </main>
</body>
</html>
`;

  const readme = `# ${appName}

${prompt}

## Run locally

npm install

npm run dev

Open the local URL printed in the terminal.

## Generated by Ember

This starter is intentionally local-first and uses sample data.
`;

  const files: TemplateFile[] = [
    {
      path: "package.json",
      language: "json",
      purpose: "Project dependencies and scripts.",
      content: packageJson,
    },
    {
      path: "next.config.mjs",
      language: "javascript",
      purpose: "Next.js configuration.",
      content: nextConfig,
    },
    {
      path: "next-env.d.ts",
      language: "ts",
      purpose: "Next.js type declarations.",
      content: nextEnv,
    },
    {
      path: "tsconfig.json",
      language: "json",
      purpose: "TypeScript configuration.",
      content: tsconfigJson,
    },
    {
      path: "app/layout.tsx",
      language: "tsx",
      purpose: "Root app layout.",
      content: layoutTsx,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      purpose: "Main generated app.",
      content: pageTsx,
    },
    {
      path: "app/globals.css",
      language: "css",
      purpose: "Global styles and app classes.",
      content: globalsCss,
    },
    {
      path: "README.md",
      language: "markdown",
      purpose: "Setup and run instructions.",
      content: readme,
    },
  ];

  return {
    appName,
    slug,
    platform: "web",
    framework: "Next.js",
    summary: `A local-first generated app starter for: ${prompt}`,
    previewHtml,
    previewType: "interactive_html",
    previewNotes:
      "This preview shows the generated starter app. The exported project includes a runnable Next.js app.",
    files,
    nextSteps: [
      "Export the ZIP.",
      "Run npm install.",
      "Run npm run dev.",
      "Ask Ember to add persistence, authentication, or deployment setup.",
    ],
  };
}
