import type { BusinessAppBlueprint } from "@/lib/appBuilder/blueprint";

export type GeneratedBusinessFile = {
  path: string;
  language: string;
  purpose: string;
  content: string;
};

export type RenderedBusinessApp = {
  templateId: string;
  appName: string;
  slug: string;
  platform: string;
  framework: string;
  summary: string;
  previewHtml: string;
  previewType: string;
  previewNotes: string;
  files: GeneratedBusinessFile[];
  nextSteps: string[];
};

function createPackageJson(slug: string) {
  return `{
  "name": "${slug}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.2.35",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5"
  }
}
`;
}

function createNextConfig() {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {};

export default nextConfig;
`;
}

function createNextEnv() {
  return `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file was generated by Embr.
`;
}

function createTsconfig() {
  return `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
}

function createLayout(appName: string) {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(appName)},
  description: "Generated by Embr.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function createPage(blueprint: BusinessAppBlueprint) {
  const blueprintJson = JSON.stringify(blueprint, null, 2);

  return `"use client";

import { type ChangeEvent, type FormEvent, useMemo, useState } from "react";

type FieldKind = "text" | "number" | "select" | "textarea";

type BusinessField = {
  key: string;
  label: string;
  kind: FieldKind;
  placeholder?: string;
  options?: string[];
};

type BusinessRecord = {
  id: string;
  status: string;
  data: Record<string, string>;
};

type BusinessAppBlueprint = {
  appType: string;
  appName: string;
  slug: string;
  eyebrow: string;
  title: string;
  description: string;
  primaryEntity: string;
  createTitle: string;
  actionLabel: string;
  searchPlaceholder: string;
  fields: BusinessField[];
  statuses: string[];
  closedStatuses: string[];
  titleFieldKey: string;
  contactFieldKey: string;
  valueFieldKey: string;
  followUpFieldKey: string;
  notesFieldKey: string;
  subtitleFieldKeys: string[];
  statsLabels: {
    active: string;
    value: string;
    followUp: string;
    closed: string;
  };
  samples: BusinessRecord[];
  nextSteps: string[];
};

const blueprint: BusinessAppBlueprint = ${blueprintJson};

const money = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  maximumFractionDigits: 0,
});

function getStatusClass(status: string) {
  return "status-badge " + status.toLowerCase().replace(/\\\\s+/g, "-");
}

function createEmptyForm() {
  return blueprint.fields.reduce<Record<string, string>>((result, field) => {
    result[field.key] = field.options?.[0] || "";
    return result;
  }, {});
}

function getRecordValue(record: BusinessRecord) {
  return Number(record.data[blueprint.valueFieldKey]) || 0;
}

function getRecordTitle(record: BusinessRecord) {
  return record.data[blueprint.titleFieldKey] || blueprint.primaryEntity;
}

function getRecordSubtitle(record: BusinessRecord) {
  return blueprint.subtitleFieldKeys
    .map((key) => record.data[key])
    .filter(Boolean)
    .join(" · ");
}

export default function Page() {
  const [records, setRecords] = useState<BusinessRecord[]>(blueprint.samples);
  const [search, setSearch] = useState("");
  const [form, setForm] = useState<Record<string, string>>(createEmptyForm());

  const stats = useMemo(() => {
    const activeRecords = records.filter(
      (record) => !blueprint.closedStatuses.includes(record.status),
    );

    const closedRecords = records.filter((record) =>
      blueprint.closedStatuses.includes(record.status),
    );

    const totalValue = activeRecords.reduce(
      (total, record) => total + getRecordValue(record),
      0,
    );

    const followUps = activeRecords.filter((record) => {
      const value = record.data[blueprint.followUpFieldKey];
      return value && value.toLowerCase() !== "not scheduled";
    });

    return [
      {
        label: blueprint.statsLabels.active,
        value: activeRecords.length,
        helper: "Currently moving",
      },
      {
        label: blueprint.statsLabels.value,
        value: money.format(totalValue),
        helper: "Open estimated value",
      },
      {
        label: blueprint.statsLabels.followUp,
        value: followUps.length,
        helper: "Needs next action",
      },
      {
        label: blueprint.statsLabels.closed,
        value: closedRecords.length,
        helper: "Completed or closed",
      },
    ];
  }, [records]);

  const filteredRecords = useMemo(() => {
    const query = search.trim().toLowerCase();

    if (!query) return records;

    return records.filter((record) =>
      [
        record.status,
        ...Object.values(record.data),
      ]
        .join(" ")
        .toLowerCase()
        .includes(query),
    );
  }, [records, search]);

  function handleChange(
    event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>,
  ) {
    const { name, value } = event.target;

    setForm((current) => ({
      ...current,
      [name]: value,
    }));
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const titleValue = form[blueprint.titleFieldKey]?.trim();

    if (!titleValue) return;

    const newRecord: BusinessRecord = {
      id: "record-" + Date.now(),
      status: blueprint.statuses[0] || "New",
      data: { ...form },
    };

    setRecords((current) => [newRecord, ...current]);
    setForm(createEmptyForm());
  }

  function moveStatus(id: string) {
    setRecords((current) =>
      current.map((record) => {
        if (record.id !== id) return record;

        const currentIndex = blueprint.statuses.indexOf(record.status);
        const nextStatus =
          blueprint.statuses[(currentIndex + 1) % blueprint.statuses.length] ||
          blueprint.statuses[0] ||
          record.status;

        return {
          ...record,
          status: nextStatus,
        };
      }),
    );
  }

  function renderField(field: BusinessField) {
    if (field.kind === "textarea") {
      return (
        <textarea
          id={field.key}
          name={field.key}
          value={form[field.key] || ""}
          onChange={handleChange}
          placeholder={field.placeholder || field.label}
          rows={4}
        />
      );
    }

    if (field.kind === "select") {
      return (
        <select
          id={field.key}
          name={field.key}
          value={form[field.key] || field.options?.[0] || ""}
          onChange={handleChange}
        >
          {(field.options || []).map((option) => (
            <option key={option}>{option}</option>
          ))}
        </select>
      );
    }

    return (
      <input
        id={field.key}
        name={field.key}
        value={form[field.key] || ""}
        onChange={handleChange}
        type={field.kind === "number" ? "number" : "text"}
        min={field.kind === "number" ? "0" : undefined}
        placeholder={field.placeholder || field.label}
        required={field.key === blueprint.titleFieldKey}
      />
    );
  }

  return (
    <main className="page-shell">
      <section className="hero-card">
        <div>
          <p className="eyebrow">{blueprint.eyebrow}</p>
          <h1>{blueprint.title}</h1>
          <p className="hero-copy">{blueprint.description}</p>
        </div>
      </section>

      <section className="stat-grid" aria-label="Business overview">
        {stats.map((stat) => (
          <article className="stat-card" key={stat.label}>
            <span>{stat.label}</span>
            <strong>{stat.value}</strong>
            <p>{stat.helper}</p>
          </article>
        ))}
      </section>

      <section className="dashboard-grid">
        <article className="panel">
          <div className="panel-heading">
            <p className="eyebrow">Create</p>
            <h2>{blueprint.createTitle}</h2>
          </div>

          <form className="stacked-form" onSubmit={handleSubmit}>
            {blueprint.fields.map((field) => (
              <div className="form-row" key={field.key}>
                <label htmlFor={field.key}>{field.label}</label>
                {renderField(field)}
              </div>
            ))}

            <button className="button primary full-width" type="submit">
              {blueprint.actionLabel}
            </button>
          </form>
        </article>

        <article className="panel">
          <div className="panel-heading split">
            <div>
              <p className="eyebrow">Workspace</p>
              <h2>{blueprint.primaryEntity}</h2>
            </div>

            <label className="search-label" htmlFor="search">
              <span className="sr-only">Search</span>
              <input
                id="search"
                type="search"
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder={blueprint.searchPlaceholder}
              />
            </label>
          </div>

          <div className="record-list">
            {filteredRecords.map((record) => (
              <div className="record-card" key={record.id}>
                <div className="record-topline">
                  <div>
                    <h3>{getRecordTitle(record)}</h3>
                    <p>{getRecordSubtitle(record)}</p>
                  </div>

                  <span className={getStatusClass(record.status)}>
                    {record.status}
                  </span>
                </div>

                <p className="record-note">
                  {record.data[blueprint.notesFieldKey] || "No notes yet."}
                </p>

                <div className="record-meta">
                  <span>{record.data[blueprint.contactFieldKey] || "No contact"}</span>
                  <span>{money.format(getRecordValue(record))}</span>
                  <span>
                    Follow-up: {record.data[blueprint.followUpFieldKey] || "Not scheduled"}
                  </span>
                  <button
                    className="table-action"
                    type="button"
                    onClick={() => moveStatus(record.id)}
                  >
                    Move status
                  </button>
                </div>
              </div>
            ))}
          </div>
        </article>
      </section>
    </main>
  );
}
`;
}

function createGlobalsCss() {
  return `:root {
  --background: #f4f6f8;
  --surface: #ffffff;
  --surface-soft: #f8fafc;
  --text: #142033;
  --muted: #64748b;
  --border: #d8dee8;
  --primary: #1f3a5f;
  --primary-dark: #152a43;
  --shadow: 0 10px 24px rgba(15, 23, 42, 0.07);
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background: var(--background);
  color: var(--text);
  font-family:
    Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
    sans-serif;
}

button,
input,
select,
textarea {
  font: inherit;
}

.page-shell {
  width: min(1280px, calc(100% - 32px));
  margin: 0 auto;
  padding: 24px 0 40px;
}

.hero-card,
.panel,
.stat-card {
  background: var(--surface);
  border: 1px solid var(--border);
  box-shadow: var(--shadow);
}

.hero-card {
  border-radius: 14px;
  padding: 24px;
  margin-bottom: 18px;
}

.eyebrow {
  margin: 0 0 8px;
  color: var(--primary);
  font-size: 0.78rem;
  text-transform: uppercase;
  letter-spacing: 0.12em;
  font-weight: 800;
}

h1,
h2,
h3,
p {
  margin-top: 0;
}

h1 {
  margin-bottom: 8px;
  font-size: clamp(2rem, 3vw, 2.8rem);
  line-height: 1.05;
}

h2 {
  margin-bottom: 0;
  font-size: 1.35rem;
}

h3 {
  margin-bottom: 4px;
  font-size: 1rem;
}

.hero-copy {
  max-width: 820px;
  color: var(--muted);
  font-size: 0.98rem;
  line-height: 1.55;
  margin-bottom: 0;
}

.stat-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(150px, 1fr));
  gap: 12px;
  margin-bottom: 18px;
}

.stat-card {
  border-radius: 12px;
  padding: 16px;
  min-height: 112px;
}

.stat-card span {
  color: var(--muted);
  font-size: 0.9rem;
  font-weight: 700;
}

.stat-card strong {
  display: block;
  margin: 6px 0;
  font-size: 1.75rem;
}

.stat-card p {
  margin: 0;
  color: var(--muted);
  line-height: 1.5;
}

.dashboard-grid {
  display: grid;
  grid-template-columns: minmax(0, 0.95fr) minmax(0, 1.05fr);
  gap: 16px;
  margin-bottom: 16px;
}

.panel {
  border-radius: 12px;
  padding: 18px;
}

.panel-heading {
  margin-bottom: 18px;
}

.panel-heading.split {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  align-items: center;
}

.stacked-form {
  display: grid;
  gap: 12px;
}

.form-row {
  display: grid;
  gap: 7px;
}

label {
  color: var(--muted);
  font-size: 0.86rem;
  font-weight: 800;
}

input,
select,
textarea {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 10px 12px;
  background: white;
  color: var(--text);
  outline: none;
}

input:focus,
select:focus,
textarea:focus {
  border-color: var(--primary);
  box-shadow: 0 0 0 4px rgba(31, 58, 95, 0.12);
}

.button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: 0;
  border-radius: 999px;
  padding: 12px 18px;
  font-weight: 800;
  text-decoration: none;
  cursor: pointer;
}

.button.primary {
  background: var(--primary);
  color: white;
}

.full-width {
  width: 100%;
}

.record-list {
  display: grid;
  gap: 14px;
}

.record-card {
  border: 1px solid var(--border);
  background: var(--surface-soft);
  border-radius: 12px;
  padding: 16px;
}

.record-topline,
.record-meta {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  align-items: flex-start;
  flex-wrap: wrap;
}

.record-topline p,
.record-note {
  color: var(--muted);
  margin-bottom: 0;
  line-height: 1.5;
}

.record-note {
  margin: 12px 0;
}

.record-meta {
  color: var(--muted);
  font-size: 0.83rem;
}

.status-badge {
  display: inline-flex;
  align-items: center;
  white-space: nowrap;
  border-radius: 999px;
  padding: 6px 10px;
  font-size: 0.75rem;
  font-weight: 900;
  background: #e2e8f0;
  color: #334155;
}

.status-badge.contacted,
.status-badge.showing,
.status-badge.sent,
.status-badge.active {
  background: #dbeafe;
  color: #1d4ed8;
}

.status-badge.offer,
.status-badge.review,
.status-badge.overdue {
  background: #fef3c7;
  color: #92400e;
}

.status-badge.closed,
.status-badge.done,
.status-badge.paid {
  background: #dcfce7;
  color: #166534;
}

.status-badge.lost {
  background: #fee2e2;
  color: #991b1b;
}

.search-label {
  min-width: 240px;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
}

.table-action {
  border: 1px solid var(--border);
  background: white;
  border-radius: 999px;
  padding: 8px 12px;
  cursor: pointer;
  font-weight: 800;
}

@media (max-width: 1100px) {
  .stat-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .dashboard-grid {
    grid-template-columns: 1fr;
  }

  .panel-heading.split {
    flex-direction: column;
    align-items: flex-start;
  }

  .search-label {
    width: 100%;
    min-width: 0;
  }
}

@media (max-width: 640px) {
  .stat-grid {
    grid-template-columns: 1fr;
  }

  .page-shell {
    width: min(100% - 20px, 1280px);
    padding: 16px 0 28px;
  }

  .hero-card,
  .panel {
    padding: 16px;
  }
}
`;
}

function createPreviewHtml(blueprint: BusinessAppBlueprint) {
  const active = blueprint.samples.filter(
    (item) => !blueprint.closedStatuses.includes(item.status),
  ).length;

  const totalValue = blueprint.samples.reduce((sum, item) => {
    return sum + (Number(item.data[blueprint.valueFieldKey]) || 0);
  }, 0);

  const sampleCards = blueprint.samples
    .slice(0, 3)
    .map((item) => {
      const title = item.data[blueprint.titleFieldKey] || blueprint.primaryEntity;
      const subtitle = blueprint.subtitleFieldKeys
        .map((key) => item.data[key])
        .filter(Boolean)
        .join(" · ");

      return `<div class="card"><strong>${title}</strong><p>${subtitle} · ${item.status}</p></div>`;
    })
    .join("");

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${blueprint.appName} Preview</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #f4f6f8; color: #142033; }
    .shell { max-width: 430px; margin: 0 auto; min-height: 100vh; background: white; box-shadow: 0 10px 24px rgba(15,23,42,.12); }
    .hero { background: linear-gradient(135deg, #1f3a5f, #2f4f6f); color: white; padding: 28px; border-radius: 0 0 20px 20px; }
    .badge { display: inline-flex; background: rgba(255,255,255,.18); border-radius: 999px; padding: 7px 10px; font-size: 12px; font-weight: 800; margin-bottom: 14px; }
    h1 { margin: 0 0 10px; font-size: 30px; line-height: 1; }
    p { margin: 0; line-height: 1.5; }
    .content { padding: 22px; display: grid; gap: 14px; }
    .stats { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
    .card { border: 1px solid #d8dee8; border-radius: 14px; padding: 16px; background: #f8fafc; }
    .label { color: #64748b; font-size: 12px; font-weight: 800; }
    .value { display: block; margin-top: 6px; font-size: 24px; font-weight: 900; }
  </style>
</head>
<body>
  <main class="shell">
    <section class="hero">
      <div class="badge">${blueprint.eyebrow}</div>
      <h1>${blueprint.appName}</h1>
      <p>${blueprint.description}</p>
    </section>

    <section class="content">
      <div class="stats">
        <div class="card"><div class="label">${blueprint.statsLabels.active}</div><strong class="value">${active}</strong></div>
        <div class="card"><div class="label">${blueprint.statsLabels.value}</div><strong class="value">$${Math.round(totalValue / 1000)}k</strong></div>
        <div class="card"><div class="label">Total ${blueprint.primaryEntity}</div><strong class="value">${blueprint.samples.length}</strong></div>
        <div class="card"><div class="label">${blueprint.statsLabels.followUp}</div><strong class="value">${active}</strong></div>
      </div>

      ${sampleCards}
    </section>
  </main>
</body>
</html>`;
}

export function renderBusinessApp(blueprint: BusinessAppBlueprint): RenderedBusinessApp {
  const files: GeneratedBusinessFile[] = [
    {
      path: "package.json",
      language: "json",
      purpose: "Project dependencies and scripts.",
      content: createPackageJson(blueprint.slug),
    },
    {
      path: "next.config.mjs",
      language: "javascript",
      purpose: "Next.js configuration.",
      content: createNextConfig(),
    },
    {
      path: "next-env.d.ts",
      language: "ts",
      purpose: "Next.js type declarations.",
      content: createNextEnv(),
    },
    {
      path: "tsconfig.json",
      language: "json",
      purpose: "TypeScript configuration.",
      content: createTsconfig(),
    },
    {
      path: "app/layout.tsx",
      language: "tsx",
      purpose: "Root app layout.",
      content: createLayout(blueprint.appName),
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      purpose: "Main generated business app.",
      content: createPage(blueprint),
    },
    {
      path: "app/globals.css",
      language: "css",
      purpose: "Global styles and app classes.",
      content: createGlobalsCss(),
    },
    {
      path: "README.md",
      language: "markdown",
      purpose: "Setup and run instructions.",
      content: `# ${blueprint.appName}

${blueprint.description}

## Run locally

npm install

npm run dev

Open the local URL printed in the terminal.

## Generated by Embr

This starter is intentionally local-first and uses sample data.
`,
    },
  ];

  return {
    templateId: blueprint.appType,
    appName: blueprint.appName,
    slug: blueprint.slug,
    platform: "business_tool",
    framework: "Next.js",
    summary: blueprint.description,
    previewHtml: createPreviewHtml(blueprint),
    previewType: "interactive_html",
    previewNotes:
      "This preview shows the generated business app layout. The exported project includes a runnable Next.js app.",
    files,
    nextSteps: blueprint.nextSteps,
  };
}
