import JSZip from "jszip";
import { NextRequest, NextResponse } from "next/server";
import { getUserFromRequest, isAuthError } from "@/lib/authServer";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

function safeFileName(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "generated-app"
  );
}

function isSafePath(path: string) {
  if (!path) return false;
  if (path.startsWith("/")) return false;
  if (path.includes("..")) return false;
  if (path.includes("\\")) return false;
  return true;
}

export async function GET(req: NextRequest) {
  try {
    const user = await getUserFromRequest(req);

    const { searchParams } = new URL(req.url);
    const id = searchParams.get("id")?.trim();

    if (!id) {
      return NextResponse.json(
        { success: false, error: "Generated app id is required." },
        { status: 400 }
      );
    }

    const { data: app, error: appError } = await supabaseAdmin
      .from("generated_apps")
      .select(
        "id, name, platform, framework, status, summary, build_prompt, preview_html, preview_type, preview_notes, created_at, updated_at"
      )
      .eq("id", id)
      .eq("user_id", user.id)
      .maybeSingle();

    if (appError) {
      throw appError;
    }

    if (!app) {
      return NextResponse.json(
        { success: false, error: "Generated app not found." },
        { status: 404 }
      );
    }

    const { data: files, error: filesError } = await supabaseAdmin
      .from("generated_app_files")
      .select("path, content, language, purpose")
      .eq("generated_app_id", id)
      .eq("user_id", user.id)
      .order("path", { ascending: true });

    if (filesError) {
      throw filesError;
    }

    const zip = new JSZip();
    const rootName = safeFileName(app.name);
    const root = zip.folder(rootName);

    if (!root) {
      throw new Error("Could not create ZIP folder.");
    }

    for (const file of files || []) {
      if (!isSafePath(file.path)) continue;
      root.file(file.path, file.content || "");
    }

    if (app.preview_html) {
      root.file("preview.html", app.preview_html);
    }

    root.file(
      "ember-generated-app.json",
      JSON.stringify(
        {
          id: app.id,
          name: app.name,
          platform: app.platform,
          framework: app.framework,
          status: app.status,
          summary: app.summary,
          buildPrompt: app.build_prompt,
          previewType: app.preview_type,
          previewNotes: app.preview_notes,
          createdAt: app.created_at,
          updatedAt: app.updated_at,
          exportedAt: new Date().toISOString(),
          files: (files || []).map((file) => ({
            path: file.path,
            language: file.language,
            purpose: file.purpose,
          })),
        },
        null,
        2
      )
    );

    const hasReadme = (files || []).some((file) =>
      file.path.toLowerCase().endsWith("readme.md")
    );

    if (!hasReadme) {
      root.file(
        "README.md",
        `# ${app.name}

${app.summary || "Generated by Ember."}

## Platform

${app.platform}

## Framework

${app.framework}

## Build Prompt

${app.build_prompt}

## Notes

This project was generated by Ember. Review the files, install dependencies if needed, and run the app according to the framework.

`
      );
    }

    const zipBuffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: {
        level: 6,
      },
    });

    const fileName = `${rootName}.zip`;

    return new NextResponse(new Uint8Array(zipBuffer), {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    console.error("EXPORT GENERATED APP ERROR:", error);

    if (isAuthError(error)) {
      return NextResponse.json(
        { success: false, error: "You need to log in first." },
        { status: 401 }
      );
    }

    return NextResponse.json(
      { success: false, error: "Could not export generated app." },
      { status: 500 }
    );
  }
}
